feat: tflint

diff --git a/shells/shared/functions b/shells/shared/functions
--- a/shells/shared/functions
+++ b/shells/shared/functions
@@ -16,6 +16,13 @@ hadolint() {
   fi
 }
 
+tflint() {
+  if ! "$HOME/.system_scripts/tflint.sh"; then
+    echo "Error: tflint.sh failed" >&2
+    return 1
+  fi
+}
+
 gen_env_example() {
   if [[ ! -f .env ]]; then
     echo ".env file not found!" >&2
